--- Delete any rows already sitting at SYSDATE+1 to avoid unique constraint errors.
--- FIU_eRAC_APPROVAL is the process identifier embedded in EOAWCRTA_ID.

DELETE PS_EOAW_PATH       WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TRUNC(SYSDATE+1);
DELETE PS_EOAW_PRCS       WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TRUNC(SYSDATE+1);
DELETE PS_EOAW_STAGE      WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TRUNC(SYSDATE+1);
DELETE PS_EOAW_STEP       WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TRUNC(SYSDATE+1);
DELETE PS_EOAW_TIMEOUT    WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TRUNC(SYSDATE+1);
DELETE PS_EOAW_TIMEOUTDEF WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TRUNC(SYSDATE+1);
DELETE PS_EOAWCRTA_REC    WHERE EOAWCRTA_ID LIKE '%FIU_eRAC_APPROVAL%' || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') || '%';
DELETE PS_EOAWCRTA_VAL    WHERE EOAWCRTA_ID LIKE '%FIU_eRAC_APPROVAL%' || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') || '%';
DELETE PS_EOAWCRTA        WHERE EOAWCRTA_ID LIKE '%FIU_eRAC_APPROVAL%' || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') || '%';

--- Mark previous Process Definition as non-default (EOAWDEFN_DEFAULT = N).

--- TODO: Replace <DD-MON-YYYY> with the previous effective date before running.
-- UPDATE PS_EOAW_PRCS SET EOAWDEFN_DEFAULT = 'N' WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TO_DATE('<DD-MON-YYYY>','DD-MON-YYYY');

--- Shift effective date from 2022-07-23 to SYSDATE+1.
--- The year token '2022' in EOAWCRTA_ID is replaced with the new YYYY-MM-DD date.

UPDATE PS_EOAW_PATH A SET EFFDT = TRUNC(SYSDATE+1), EOAWCRTA_ID = SUBSTR(A.EOAWCRTA_ID, 1, INSTR(A.EOAWCRTA_ID, '2022')-1) || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') || (CASE WHEN INSTR(A.EOAWCRTA_ID, '-NextID') <> 0 THEN SUBSTR(A.EOAWCRTA_ID, INSTR(A.EOAWCRTA_ID, '-NextID'), LENGTH(A.EOAWCRTA_ID)-1) ELSE '' END) WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TO_DATE('23-JUL-2022','DD-MON-YYYY');

UPDATE PS_EOAW_PRCS A SET EFFDT = TRUNC(SYSDATE+1), A.EOAWCRTA_ID = SUBSTR(A.EOAWCRTA_ID, 1, INSTR(A.EOAWCRTA_ID, '2022')-1) || TO_CHAR(SYSDATE+1,'YYYY-MM-DD'), A.EOAWDEFN_CRTA_ID = SUBSTR(A.EOAWCRTA_ID, 1, INSTR(A.EOAWCRTA_ID, '2022')-1) || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') WHERE A.EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND A.EFFDT = TO_DATE('23-JUL-2022','DD-MON-YYYY');

UPDATE PS_EOAW_STAGE SET EFFDT = TRUNC(SYSDATE+1) WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TO_DATE('23-JUL-2022','DD-MON-YYYY');

UPDATE PS_EOAW_STEP A SET EFFDT = TRUNC(SYSDATE+1), EOAWSELF_CRTA_ID = SUBSTR(A.EOAWSELF_CRTA_ID, 1, INSTR(A.EOAWSELF_CRTA_ID, '2022')-1) || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') || (CASE WHEN INSTR(A.EOAWSELF_CRTA_ID, '-NextID') <> 0 THEN SUBSTR(A.EOAWSELF_CRTA_ID, INSTR(A.EOAWSELF_CRTA_ID, '-NextID'), LENGTH(A.EOAWSELF_CRTA_ID)-1) ELSE '' END), EOAWCRTA_ID = SUBSTR(A.EOAWCRTA_ID, 1, INSTR(A.EOAWCRTA_ID, '2022')-1) || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') || (CASE WHEN INSTR(A.EOAWCRTA_ID, '-NextID') <> 0 THEN SUBSTR(A.EOAWCRTA_ID, INSTR(A.EOAWCRTA_ID, '-NextID'), LENGTH(A.EOAWCRTA_ID)-1) ELSE '' END) WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TO_DATE('23-JUL-2022','DD-MON-YYYY');

UPDATE PS_EOAW_TIMEOUT SET EFFDT = TRUNC(SYSDATE+1) WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TO_DATE('23-JUL-2022','DD-MON-YYYY');

UPDATE PS_EOAW_TIMEOUTDEF SET EFFDT = TRUNC(SYSDATE+1) WHERE EOAWPRCS_ID = 'FIU_eRAC_APPROVAL' AND EFFDT = TO_DATE('23-JUL-2022','DD-MON-YYYY');

UPDATE PS_EOAWCRTA_REC A SET EOAWCRTA_ID = SUBSTR(A.EOAWCRTA_ID, 1, INSTR(A.EOAWCRTA_ID, '2022')-1) || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') || (CASE WHEN INSTR(A.EOAWCRTA_ID, '-NextID') <> 0 THEN SUBSTR(A.EOAWCRTA_ID, INSTR(A.EOAWCRTA_ID, '-NextID'), LENGTH(A.EOAWCRTA_ID)-1) ELSE '' END) WHERE EOAWCRTA_ID LIKE '%FIU_eRAC_APPROVAL%2022-07-23%';

UPDATE PS_EOAWCRTA_VAL A SET EOAWCRTA_ID = SUBSTR(A.EOAWCRTA_ID, 1, INSTR(A.EOAWCRTA_ID, '2022')-1) || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') || (CASE WHEN INSTR(A.EOAWCRTA_ID, '-NextID') <> 0 THEN SUBSTR(A.EOAWCRTA_ID, INSTR(A.EOAWCRTA_ID, '-NextID'), LENGTH(A.EOAWCRTA_ID)-1) ELSE '' END) WHERE EOAWCRTA_ID LIKE '%FIU_eRAC_APPROVAL%2022-07-23%';

UPDATE PS_EOAWCRTA A SET A.EOAWCRTA_ID = SUBSTR(A.EOAWCRTA_ID, 1, INSTR(A.EOAWCRTA_ID, '2022')-1) || TO_CHAR(SYSDATE+1,'YYYY-MM-DD') || (CASE WHEN INSTR(A.EOAWCRTA_ID, '-NextID') <> 0 THEN SUBSTR(A.EOAWCRTA_ID, INSTR(A.EOAWCRTA_ID, '-NextID'), LENGTH(A.EOAWCRTA_ID)-1) ELSE '' END) WHERE A.EOAWCRTA_ID LIKE '%FIU_eRAC_APPROVAL%2022-07-23%';

